using Microsoft.Owin.Security.OAuth;
using OCTWEB_NET45.Context;
using OCTWEB_NET45.Controllers.DocumentControll;
using OCTWEB_NET45.Models;
using Org.BouncyCastle.Asn1.Ocsp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using static OCTWEB_NET45.Controllers.DocumentControll.DocumentService;

namespace OCTWEB_NET45.Controllers.DocumentControll
{
    public class DocumentNotification
    {
        #region Notification Service
    
        public static class NotificationService
        {
            public static string SendApprovalRequestEmail(List<string> to, string subject, List<string> cc, int LId, UrlHelper url, HttpRequestBase request)
            {
                try
                {
                    var callbackUrl = url.Action("Details", "Document", new { id = LId }, protocol: request.Url.Scheme);

                    string html = $@"
                        <div style='font-family:Tahoma, sans-serif; font-size:14px; line-height:1.8; padding-left:20px;'>
                            
                           
                            <p><b>Dear Department Head,</b></p>

                            <p style='text-indent:2em;'>
                                There is a new document action request pending your approval in the OCT WEB system. 
                                Please review and take action within 3 working days.
                            </p>

                            <p style='text-indent:2em;'>
                                🔗 <a href='{callbackUrl}' target='_blank'>Click here to open OCT WEB - Document Control</a>
                            </p>

                            <br />

                            <hr style='border: none; border-top: 1px solid #ccc; margin: 20px 0;' />
                            <p><b>เรียน หัวหน้าแผนก,</b></p>

                            <p style='text-indent:2em;'>
                                มีคำร้องขอดำเนินการเอกสาร (Document action request) ที่ต้องการการอนุมัติ กรุณาดำเนินการตรวจสอบและอนุมัติภายใน 3 วันทำการ
                            </p>

                            <p style='text-indent:2em;'>
                                🔗 <a href='{callbackUrl}' target='_blank'>คลิกที่นี่เพื่อเปิดระบบ OCT WEB - Document Control</a>
                            </p>

                            <br />

                            <p style='color:gray; font-size:12px;'>
                                *This email was automatically generated by the system. Please do not reply.*
                            </p>
                        </div>
                    ";

                    var model = new SendMailCenterModel
                    {
                        To = to ?? new List<string>(),
                        Tocc = cc ?? new List<string>(),
                        Subject = subject,
                        Body = html
                    };

                    SendMailCenterController.SendMail(model);
                    return "ส่งอีเมลสำเร็จ";
                }
                catch (Exception ex)
                {
                    return "เกิดข้อผิดพลาดในการส่งอีเมล: " + ex.Message;
                }
            }


            public static void SendSimpleEmail(List<string> to, string subject, string body)
            {
                try
                {
                    var model = new SendMailCenterModel
                    {
                        To = to ?? new List<string>(),
                        Tocc = new List<string>(),
                        Subject = subject,
                        Body = $"<p style='font-size: 16px'>{body}</p>"
                    };

                    SendMailCenterController.SendMail(model);
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine("Email error: " + ex.Message);
                }
            }


            public static void NotifyAfterApproval(DocumentList document, DocumentDetail documentDetail, DocumentApprovalStep currentStep, string requesterEmail, UrlHelper urlHelper, HttpRequestBase request)
            {
                using (var db = new OCTWEBTESTEntities())
                {
                    string darNo = document.DarNumber ?? "N/A";
                    string wsNo = documentDetail?.WS_number ?? $"WS-{document.LId}";
                    string wsName = documentDetail?.WS_name ?? "(ไม่ระบุชื่อเอกสาร)";
                    string updatedAt = document.Updated_at?.ToString("yyyy-MM-dd") ?? "(ไม่ระบุวันที่)";
                    string docLink = urlHelper.Action("Details", "Document", new { id = document.LId }, request.Url.Scheme);
                    var step2 = db.DocumentApprovalSteps.FirstOrDefault(s => s.LId == document.LId && s.Step == 2);
                    var step2Approver = db.UserDetails.FirstOrDefault(u => u.USE_Usercode == step2.Approver_id);
                    string StepName = StepNameHelper.GetInitialsName(document, currentStep);

                    // ----------------------------
                    // 1. แจ้งผู้ร้องขอเอกสาร (Requester)
                    // ----------------------------
                    if (!string.IsNullOrEmpty(requesterEmail))
                    {

                        string ApproverName = db.DocumentApprovalSteps
                            .Where(s => s.LId == document.LId && s.Step == currentStep.Step)
                            .OrderBy(s => s.Step)
                            .Join(db.UserDetails, s => s.Approver_id, u => u.USE_Usercode, (s, u) => u.USE_FName + " " + u.USE_LName)
                            .FirstOrDefault() ?? "ระบบ";

                        string requesterBody = $@"
                        <div style='font-family:Tahoma, sans-serif; font-size:14px; line-height:1.7; padding-left:20px;'>

                            <p><b>เรียน ผู้ร้องขอ,</b></p>

                            <p style='text-indent: 2em;'>
                                คำร้องขอดำเนินการเอกสารหมายเลข <b>{wsNo}</b> ได้รับการอนุมัติแล้ว<br/>
                                โดยผู้อนุมัติ: <b>{ApproverName} ({StepName})</b>
                            </p>

                            <p style='text-indent: 2em;'>
                                🔗 <a href='{docLink}' target='_blank'>คลิกที่นี่เพื่อเปิดเอกสาร</a>
                            </p>

                            <br/>

                            <p style='color:gray; font-size:12px;'>
                                **อีเมลฉบับนี้ส่งจากระบบอัตโนมัติ กรุณาอย่าตอบกลับ**
                            </p>
                        </div>";

                        NotificationService.SendSimpleEmail(
                            to: new List<string> { requesterEmail },
                            subject: $"คำร้องขอดำเนินการเอกสาร WS No: {wsNo} ได้รับการอนุมัติจาก {StepName} แล้ว",
                            body: requesterBody
                        );
                    }

                    // ----------------------------
                    // 2. แจ้งผู้อนุมัติขั้นตอนถัดไป
                    // ----------------------------
                    var nextStep = db.DocumentApprovalSteps
                        .Where(s => s.LId == document.LId && s.Step > currentStep.Step)
                        .OrderBy(s => s.Step)
                        .FirstOrDefault();

                    if (nextStep != null)
                    {
                        var nextApprover = db.UserDetails.FirstOrDefault(u => u.USE_Usercode == nextStep.Approver_id);
                        if (!string.IsNullOrEmpty(nextApprover?.USE_Email))
                        {
                            string nextApproverBody = $@"
                            <div style='font-family:Tahoma, sans-serif; font-size:14px; line-height:1.7; padding-left:20px;'>
                                <p><b>Dear {nextApprover.USE_FName} {nextApprover.USE_LName},</b></p>

                                <p style='text-indent: 2em;'>
                                    กรุณาตรวจสอบและดำเนินการอนุมัติคำร้องเอกสาร WS No: <b>{wsNo}</b><br/>
                                </p>
                                <p style='text-indent: 2em;'>
                                    วันที่ลงทะเบียน: <b>{updatedAt}</b>
                                </p>

                                <p style='text-indent: 2em;'>
                                    🔗 <a href='{docLink}' target='_blank'>คลิกเพื่อเปิดเอกสาร</a>
                                </p>

                                <br/>
                                <p style='color:gray; font-size:12px;'>**อีเมลฉบับนี้ส่งจากระบบอัตโนมัติ กรุณาอย่าตอบกลับ**</p>
                            </div>";

                            NotificationService.SendSimpleEmail(
                                to: new List<string> { nextApprover.USE_Email },
                                subject: $"มีคำขอดำเนินการเอกสาร รออนุมัติ WS No: {wsNo}",
                                body: nextApproverBody
                            );
                        }
                    }

                    // ----------------------------
                    // 3. แจ้ง DCC เมื่ออนุมัติ Step สุดท้าย (Step 3)
                    // ----------------------------
                    if (currentStep.Step == 3)
                    {

                        if (!string.IsNullOrEmpty(step2Approver?.USE_Email))
                        {
                            string qmrBody = $@"
                            <div style='font-family:Tahoma, sans-serif; font-size:14px; line-height:1.7; padding-left:20px;'>
                                <p><b>Dear {step2Approver.USE_FName} {step2Approver.USE_LName},</b></p>
                                
                                <p style='text-indent: 2em;'>
                                    เอกสาร WS No: <b>{wsNo}</b> ได้รับการอนุมัติโดย {StepName} เรียบร้อยแล้ว
                                </p>
                                
                                <p style='text-indent: 2em;'>
                                    🔗 <a href='{docLink}' target='_blank'>ดูรายละเอียดเอกสาร</a>
                                </p>

                                <br/>
                                <p style='color:gray; font-size:12px;'>**อีเมลฉบับนี้ส่งจากระบบอัตโนมัติ กรุณาอย่าตอบกลับ**</p>
                            </div>";

                            NotificationService.SendSimpleEmail(
                                to: new List<string> { step2Approver.USE_Email },
                                subject: $"คำขอดำเนินการเอกสาร WS No: {wsNo} ผ่านการอนุมัติแล้ว",
                                body: qmrBody
                            );
                        }
                    }
                }

            }

            public static void NotifyAfterReject(DocumentList document, DocumentDetail documentDetail, DocumentApprovalStep currentStep, string requesterEmail, UrlHelper urlHelper, HttpRequestBase request)
            {
                using (var db = new OCTWEBTESTEntities())
                {
                    string darNo = document.DarNumber ?? "N/A";
                    string wsNo = documentDetail?.WS_number ?? $"WS-{document.LId}";
                    string wsName = documentDetail?.WS_name ?? "(ไม่ระบุชื่อเอกสาร)";
                    string updatedAt = document.Updated_at?.ToString("yyyy-MM-dd") ?? "(ไม่ระบุวันที่)";
                    string docLink = urlHelper.Action("Details", "Document", new { id = document.LId }, request.Url.Scheme);
                    var step2 = db.DocumentApprovalSteps.FirstOrDefault(s => s.LId == document.LId && s.Step == 2);
                    var step2Approver = db.UserDetails.FirstOrDefault(u => u.USE_Usercode == step2.Approver_id);
                    string StepName = StepNameHelper.GetInitialsName(document, currentStep);
                   

                    if (!string.IsNullOrEmpty(requesterEmail))
                    {
                        string registrationDate = document.Updated_at?.ToString("yyyy-MM-dd") ?? "(ไม่ระบุวันที่)";
                        string subject = $"คำขอดำเนินการเอกสาร WS No: {wsNo} ถูกปฏิเสธ";
                        string body = $@"
                            <div style='font-family:Tahoma, sans-serif; font-size:14px; line-height:1.7; padding-left:20px;'>
                                <p>เรียน ผู้ร้องขอ,</p>
                                <p style='text-indent:2em;'>
                                    คำขอดำเนินการเอกสาร ws no: <b>{wsNo}</b>
                                </p>
                                <p style='text-indent:2em;'>
                                    สถานะ: <b><span style='color:red'><b>ปฏิเสธ</b></span></b>
                                </p>
                                <p style='text-indent: 2em;'>
                                    อนุมัติโดย: <b>{StepName}</b>
                                </p>
                                <p style='text-indent: 2em;'>
                                    เหตุผล: <b>{currentStep.Comment}</b>
                                </p>
                                <p style='text-indent:2em;'>
                                    🔗 <a href='{docLink}' target='_blank'>คลิกที่นี่เพื่อดูรายละเอียดเอกสาร</a>
                                </p>
                                <br/>
                                <p style='color:gray; font-size:12px;'>**อีเมลฉบับนี้ส่งจากระบบอัตโนมัติ กรุณาอย่าตอบกลับ**</p>
                            </div>";

                        NotificationService.SendSimpleEmail(
                            to: new List<string> { requesterEmail },
                            subject: subject,
                            body: body
                        );
                    }
                }

            }

            public static void NotifyProcessReviewTeamsIfNeeded(DocumentList document, DocumentDetail documentDetail, UrlHelper urlHelper, HttpRequestBase request)
            {
                // ตรวจสอบว่าเอกสารนี้ต้องการการ review หรือไม่
                bool requireFMEA = document.FMEAReview == true;
                bool requireControlPlan = document.ControlPlanReview == true;
                bool requireProcessFlow = document.ProcessFlowReview == true;

                if (!(requireFMEA || requireControlPlan || requireProcessFlow))
                    return;

                using (var db = new OCTWEBTESTEntities())
                {
                    var requiredRightIds = new[] { 77 };

                    var notifyUsers = db.UserRights
                        .Where(r => requiredRightIds.Contains(r.RIH_Id))
                        .Join(db.UserDetails, r => r.USE_Id, u => u.USE_Id, (r, u) => u)
                        .Select(u => u.USE_Email)
                        .Where(email => !string.IsNullOrEmpty(email))
                        .Distinct()
                        .ToList();

                    if (notifyUsers.Any())
                    {
                        var reviewItems = new List<string>();
                        if (requireFMEA) reviewItems.Add("FMEA");
                        if (requireControlPlan) reviewItems.Add("Control Plan");
                        if (requireProcessFlow) reviewItems.Add("Process Flow");

                        string wsNo = !string.IsNullOrEmpty(documentDetail.WS_number)
                            ? documentDetail.WS_number
                            : "N/A";

                        string wsName = documentDetail?.WS_name ?? "(ไม่ระบุชื่อเอกสาร)";
                        string darNo = document?.DarNumber ?? "N/A";
                        string registrationDate = document.Updated_at?.ToString("yyyy-MM-dd") ?? "(ไม่ระบุวันที่)";
                        string documentLink = urlHelper.Action("Details", "Document", new { id = document.LId }, request.Url.Scheme);

                        string subject = $"OCT - DocumentControl | WS No: {wsNo} ต้องการการ Review";

                        string body = $@"
                        <div style='font-family:Tahoma, sans-serif; font-size:14px; line-height:1.7; padding-left:20px;'>

                            <p><b>เรียน ผู้เกี่ยวที่ข้อง </b></p>

                            <p style='text-indent: 2em;'>
                                เอกสาร Dar No:  <b>{darNo}</b>
                            </p>
                            <p style='text-indent: 2em;'>
                                เอกสาร WS No:  <b>{wsNo}</b>
                            </p>

                            <p style='text-indent: 2em;'>                               
                                ต้องการ Review ในหัวข้อ:  <b>{string.Join(", ", reviewItems)}</b>
                            </p>

                            <p style='text-indent: 2em;'>
                                🔗 <a href='{documentLink}' target='_blank'>คลิกที่นี่เพื่อเปิดเอกสาร</a>
                            </p>

                            <br/>
                            <p style='color:gray; font-size:12px;'>**อีเมลฉบับนี้ส่งจากระบบอัตโนมัติ กรุณาอย่าตอบกลับ**</p>
                        </div>";

                        NotificationService.SendSimpleEmail(
                            to: notifyUsers,
                            subject: subject,
                            body: body
                        );
                    }
                }
            }
        }
        #endregion
    }
}