//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_BillingDetails
    {
        public int Id { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string DocumentNo { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime DueDate { get; set; }
        public double Amount { get; set; }
        public double Vat { get; set; }
        public double Total { get; set; }
        public int MasterAccBankId { get; set; }
        public int Payment { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Acc_BillingHeaderId { get; set; }
    }
}
