//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class cap_Probleminform
    {
        public int ID { get; set; }
        public string PB_Id { get; set; }
        public System.DateTime PB_Dateinform { get; set; }
        public int PB_Shift { get; set; }
        public string PB_Partname { get; set; }
        public string PB_Line { get; set; }
        public string PB_Model { get; set; }
        public string PB_LotNo { get; set; }
        public System.DateTime PB_Strtime { get; set; }
        public System.DateTime PB_Endtime { get; set; }
        public int PB_NGqty { get; set; }
        public int PB_Totalqty { get; set; }
        public string PB_Note { get; set; }
        public string PB_KeyBy { get; set; }
        public string PB_filePDF { get; set; }
        public string PB_Line300 { get; set; }
    }
}
