//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class cap_Partname
    {
        public int pn_Id { get; set; }
        public string pn_Group { get; set; }
        public string pn_Name { get; set; }
        public string pn_Remark { get; set; }
    }
}
