//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class cap_PBmain
    {
        public int ID { get; set; }
        public string pbmId { get; set; }
        public string pbmNameE { get; set; }
        public string pbmNameT { get; set; }
        public string pbmRemark { get; set; }
    }
}
