//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Problem
    {
        public CM_Problem()
        {
            this.CM_TodoList = new HashSet<CM_TodoList>();
        }
    
        public int PRB_Id { get; set; }
        public string PRB_Description { get; set; }
        public string PRB_FileDetail { get; set; }
        public string PRB_Reason { get; set; }
        public System.DateTime PRB_PlanDate { get; set; }
        public int PRB_Status { get; set; }
        public string PRB_Owner { get; set; }
        public int Dep_Id { get; set; }
        public string PRB_Number { get; set; }
    
        public virtual ICollection<CM_TodoList> CM_TodoList { get; set; }
    }
}
