//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_TodoEvidence
    {
        public int TDE_Id { get; set; }
        public string TDE_Answer { get; set; }
        public string TDE_Evidence { get; set; }
        public Nullable<System.DateTime> TDE_AnswerDate { get; set; }
        public string TDE_Approver { get; set; }
        public Nullable<System.DateTime> TDE_ApprovedDate { get; set; }
        public string TDE_Comment { get; set; }
        public int TDE_Revision { get; set; }
        public Nullable<int> TDE_Parent { get; set; }
        public string TDE_ParentDetail { get; set; }
        public string TDE_Status { get; set; }
        public int TDO_Id { get; set; }
    
        public virtual CM_TodoList CM_TodoList { get; set; }
    }
}
