//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_TodoList
    {
        public CM_TodoList()
        {
            this.CM_TodoEvidence = new HashSet<CM_TodoEvidence>();
        }
    
        public int TDO_Id { get; set; }
        public string TDO_Description { get; set; }
        public string TDO_Owner { get; set; }
        public string TDO_DefineBy { get; set; }
        public Nullable<System.DateTime> TDO_PlanDate { get; set; }
        public Nullable<int> TDO_NeedEvidence { get; set; }
        public int PRB_Id { get; set; }
        public Nullable<int> Dep_Id { get; set; }
    
        public virtual CM_Problem CM_Problem { get; set; }
        public virtual ICollection<CM_TodoEvidence> CM_TodoEvidence { get; set; }
    }
}
