//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesRecord
    {
        public string CrsRecID { get; set; }
        public string CrsGrp { get; set; }
        public Nullable<System.DateTime> CrsRecDate_Start { get; set; }
        public Nullable<System.DateTime> CrsRecDate_End { get; set; }
        public string CrsRecSubject { get; set; }
        public string CrsRecDetail { get; set; }
        public string CrsRecAttach { get; set; }
        public string CrsRecLocation { get; set; }
        public string CrsRecAddress { get; set; }
        public Nullable<decimal> CrsRecCost { get; set; }
        public Nullable<System.DateTime> CrsRecAvible { get; set; }
        public string CrsRecStatus { get; set; }
        public string CrsRecNote { get; set; }
        public string CrsRecLastEditBy { get; set; }
        public Nullable<System.DateTime> CrsRecLastEditDate { get; set; }
    }
}
