//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderHeader
    {
        public CustomerOrderHeader()
        {
            this.CustomerOrderDetails = new HashSet<CustomerOrderDetail>();
        }
    
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public int MasterNumberingRuleId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int MasterCustomerId { get; set; }
        public string CustomerOrderNo { get; set; }
        public string ContractNo { get; set; }
        public string PersonInCharge { get; set; }
        public int MasterDestinationId { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public int MasterInvoiceId { get; set; }
        public Nullable<int> MasterIncotermId { get; set; }
        public int MasterCurrencyId { get; set; }
        public bool IsDelete { get; set; }
        public bool IsComplete { get; set; }
        public int EnumCustomerOrderHeaderStatusId { get; set; }
        public int EnumOrderStatusId { get; set; }
        public int MasterDepartmentId { get; set; }
        public int MasterUserId { get; set; }
        public string TrackingCode { get; set; }
        public string OriginalPONo { get; set; }
        public decimal Amount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Vat { get; set; }
        public decimal GrandTotal { get; set; }
        public bool IsDocumentAttached { get; set; }
        public bool IsProjectAssigned { get; set; }
        public Nullable<int> MasterUserPersonInChargeId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<CustomerOrderDetail> CustomerOrderDetails { get; set; }
        public virtual MasterCustomer MasterCustomer { get; set; }
        public virtual MasterInvoice MasterInvoice { get; set; }
    }
}
