//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderDetail
    {
        public CustomerOrderDetail()
        {
            this.ShippingActualDetails = new HashSet<ShippingActualDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerOrderTemporaryDataId { get; set; }
        public int CustomerOrderHeaderId { get; set; }
        public int OrderLineNo { get; set; }
        public string Seiban { get; set; }
        public Nullable<int> MasterCustomerItemId { get; set; }
        public string CustomerItemShortName { get; set; }
        public string CustomerItemName { get; set; }
        public int MasterItemId { get; set; }
        public decimal OrderQty { get; set; }
        public int MasterUnitOrderUnitCodeId { get; set; }
        public decimal ItemQty { get; set; }
        public int MasterUnitItemUnitCodeId { get; set; }
        public decimal AltItemQty { get; set; }
        public int MasterUnitAltItemUnitCodeId { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal DiscountRate { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal VatRate { get; set; }
        public decimal Vat { get; set; }
        public decimal GrandTotal { get; set; }
        public string Remark { get; set; }
        public int EnumCustomerOrderTypeId { get; set; }
        public int EnumCustomerOrderDetailStatusId { get; set; }
        public Nullable<System.DateTime> RequestDueDate { get; set; }
        public Nullable<System.DateTime> AnswerDueDate { get; set; }
        public System.DateTime OriginalShippingDate { get; set; }
        public Nullable<System.DateTime> OffsetShippingDate { get; set; }
        public Nullable<System.DateTime> ArrivalPlanDate { get; set; }
        public int ShippingTotalCount { get; set; }
        public decimal ShippingTotalQty { get; set; }
        public decimal ShippingRestQty { get; set; }
        public decimal TotalOkQty { get; set; }
        public decimal TotalNgQty { get; set; }
        public int EnumReturnTypeId { get; set; }
        public Nullable<System.DateTime> ReplyDueDate { get; set; }
        public Nullable<System.DateTime> LastShippingDate { get; set; }
        public Nullable<System.DateTime> PickUpTime { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public string ItemName { get; set; }
        public string ItemSpec { get; set; }
        public bool IsShippingOrderCreated { get; set; }
        public bool IsCustomerInsp { get; set; }
        public bool IsDirectOrder { get; set; }
        public Nullable<int> PurchaseRequestDetailId { get; set; }
        public Nullable<int> MasterVendorId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual CustomerOrderHeader CustomerOrderHeader { get; set; }
        public virtual MasterItem MasterItem { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
        public virtual MasterUnit MasterUnit1 { get; set; }
        public virtual MasterUnit MasterUnit2 { get; set; }
        public virtual MasterVendor MasterVendor { get; set; }
        public virtual ICollection<ShippingActualDetail> ShippingActualDetails { get; set; }
    }
}
