//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryTagPlan
    {
        public int DEP_ID { get; set; }
        public string DEP_MPDDocid { get; set; }
        public string DEP_StkCode { get; set; }
        public string DEP_StkDrawingNo { get; set; }
        public string DEP_CustomerPartName { get; set; }
        public string DEP_CustomerPartNo { get; set; }
        public decimal DEP_PackQty { get; set; }
        public string DEP_UnitName { get; set; }
        public string DEP_CustomerCode { get; set; }
        public string DEP_CustomerName { get; set; }
        public string DEP_CountBox { get; set; }
        public string DEP_FullBox { get; set; }
        public string DEP_Memo { get; set; }
        public string DEP_ReceiveStatus { get; set; }
    }
}
