//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDetail
    {
        public int DId { get; set; }
        public int Doc_id { get; set; }
        public string WS_number { get; set; }
        public string WS_name { get; set; }
        public string Revision { get; set; }
        public string Num_pages { get; set; }
        public Nullable<int> Num_copies { get; set; }
        public string File_excel { get; set; }
        public string File_pdf { get; set; }
        public string Change_detail { get; set; }
    }
}
