//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentList
    {
        public int LId { get; set; }
        public string Request_from { get; set; }
        public string Request_type { get; set; }
        public int Requester_id { get; set; }
        public string Document_type { get; set; }
        public System.DateTime Effective_date { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<bool> FMEAReview { get; set; }
        public Nullable<bool> ControlPlanReview { get; set; }
        public Nullable<bool> ProcessFlowReview { get; set; }
        public string DarNumber { get; set; }
    }
}
