//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentActivityLog
    {
        public int log_id { get; set; }
        public Nullable<int> Doc_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string detail { get; set; }
    }
}
