//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DW_Fileshare
    {
        public int SF_Id { get; set; }
        public string SF_name { get; set; }
        public string SF_file { get; set; }
        public int SF_rev { get; set; }
        public System.DateTime SF_date { get; set; }
        public string SF_note { get; set; }
    }
}
