//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DW_Formulas
    {
        public int FOR_ID { get; set; }
        public int FOR_Parent { get; set; }
        public int FOR_Child { get; set; }
        public float FOR_Qty { get; set; }
        public string FOR_UnitName { get; set; }
        public string FOR_Note { get; set; }
        public string FOR_Not2 { get; set; }
    }
}
