//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DW_Model
    {
        public int MOD_ID { get; set; }
        public string MOD_Level { get; set; }
        public string MOD_DrawingNumber { get; set; }
        public string MOD_Rev { get; set; }
        public string MOD_Name { get; set; }
        public string MOD_SemiAssemblyNo { get; set; }
        public string MOD_CustomerNo { get; set; }
        public string MOD_FilePath { get; set; }
        public string MOD_PartListFilePath { get; set; }
        public string MOD_Note { get; set; }
        public string MOD_Note2 { get; set; }
        public Nullable<int> MOD_Hide { get; set; }
        public Nullable<int> MOD_Lock { get; set; }
        public Nullable<int> PAR_ID { get; set; }
        public string MOD_TempPartName { get; set; }
    
        public virtual DW_PartName DW_PartName { get; set; }
    }
}
