//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DW_ModelProcess
    {
        public int MOP_ID { get; set; }
        public string MOP_DrawingNumber { get; set; }
        public string MOP_Rev { get; set; }
        public string MOP_Name { get; set; }
        public string MOP_FilePath { get; set; }
        public string MOP_Note1 { get; set; }
        public string MOP_Note2 { get; set; }
        public Nullable<int> MOP_Hide { get; set; }
        public Nullable<int> MOP_Lock { get; set; }
        public Nullable<int> PRO_ID { get; set; }
        public Nullable<int> PAR_ID { get; set; }
        public string ProcessName { get; set; }
        public string PartName { get; set; }
    
        public virtual DW_PartName DW_PartName { get; set; }
        public virtual DW_Process DW_Process { get; set; }
    }
}
