//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DW_PartName
    {
        public DW_PartName()
        {
            this.DW_Model = new HashSet<DW_Model>();
            this.DW_ModelProcess = new HashSet<DW_ModelProcess>();
            this.DW_Process = new HashSet<DW_Process>();
        }
    
        public int PAR_ID { get; set; }
        public string PAR_Name { get; set; }
    
        public virtual ICollection<DW_Model> DW_Model { get; set; }
        public virtual ICollection<DW_ModelProcess> DW_ModelProcess { get; set; }
        public virtual ICollection<DW_Process> DW_Process { get; set; }
    }
}
