//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DW_Process
    {
        public DW_Process()
        {
            this.DW_ModelProcess = new HashSet<DW_ModelProcess>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_Name { get; set; }
        public int PRO_Sequence { get; set; }
        public int PAR_ID { get; set; }
    
        public virtual ICollection<DW_ModelProcess> DW_ModelProcess { get; set; }
        public virtual DW_PartName DW_PartName { get; set; }
    }
}
