//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWPic
    {
        public string LogID { get; set; }
        public string LineName { get; set; }
        public string DWlevel { get; set; }
        public string DWNo { get; set; }
        public string SemiassemblyNo { get; set; }
        public string Rev { get; set; }
        public string PartsNo { get; set; }
        public string ModelNo { get; set; }
        public string CustomerNo { get; set; }
        public string PicPart { get; set; }
        public string PList { get; set; }
        public string Remark { get; set; }
        public string DWGDes { get; set; }
        public string New_PartName { get; set; }
    }
}
