//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Transection_Leave
    {
        public int Id { get; set; }
        public int Emp_Id { get; set; }
        public System.DateTime DateSt { get; set; }
        public System.DateTime Leave_startdate { get; set; }
        public System.DateTime Leave_enddate { get; set; }
        public string Leave_time { get; set; }
        public string Leave_timeend { get; set; }
        public string Shift { get; set; }
        public double Date_leave { get; set; }
        public double Date_Hour { get; set; }
        public string Reasons_for_leave { get; set; }
        public int Type_ReasonId { get; set; }
        public string Approved_emp { get; set; }
        public string ReasonnotApEmp { get; set; }
        public string Approved_hr { get; set; }
        public string ReasonnotApHr { get; set; }
        public string Status_pay { get; set; }
        public string M_certificate { get; set; }
        public Nullable<System.DateTime> DT_UpEmpN { get; set; }
        public Nullable<System.DateTime> DT_UpHRN { get; set; }
        public string AddbyEmp { get; set; }
        public string AddAppbyHr { get; set; }
        public Nullable<int> Status_SunSat { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status_SendmailHR { get; set; }
        public Nullable<int> StatusWork { get; set; }
        public string StatusWorkDetail { get; set; }
        public string Status_hrchk { get; set; }
        public string Status_hrchkChar { get; set; }
    }
}
