//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Typesick
    {
        public Emp_Typesick()
        {
            this.Emp_SickLeave = new HashSet<Emp_SickLeave>();
        }
    
        public int Id { get; set; }
        public string Type_Reason { get; set; }
    
        public virtual ICollection<Emp_SickLeave> Emp_SickLeave { get; set; }
    }
}
