//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Benefite
    {
        public int Id { get; set; }
        public string EmpId { get; set; }
        public string Dep { get; set; }
        public string TypeBenef { get; set; }
        public string Relation { get; set; }
        public string TRName { get; set; }
        public string FRName { get; set; }
        public string LRName { get; set; }
        public string Months { get; set; }
        public string Years { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Document { get; set; }
    }
}
