//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_TrainingDetail
    {
        public int Id { get; set; }
        public int E_TrainHeader { get; set; }
        public string Emp_Id { get; set; }
        public Nullable<int> Trian_SkillKnow { get; set; }
    
        public virtual Emp_TrainingHeader Emp_TrainingHeader { get; set; }
    }
}
