//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_offense
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public string Warning_Reason { get; set; }
        public int Level_warning_Id { get; set; }
        public Nullable<int> Penalty_Id { get; set; }
        public string Date_mistake { get; set; }
        public Nullable<System.DateTime> dateLayoff_emp { get; set; }
        public Nullable<System.DateTime> Stop_wkStart { get; set; }
        public Nullable<System.DateTime> Stop_wkEnd { get; set; }
        public Nullable<System.DateTime> date_Stmistake { get; set; }
        public Nullable<System.DateTime> date_timenow { get; set; }
        public string day_shift { get; set; }
        public Nullable<System.DateTime> Exprie_mt_date { get; set; }
        public Nullable<int> Exprie_mt { get; set; }
        public string Detail_Reason { get; set; }
    
        public virtual Emp_offense_Levelwarning Emp_offense_Levelwarning { get; set; }
        public virtual Emp_offense_Penalty Emp_offense_Penalty { get; set; }
    }
}
