//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_offense_Penalty
    {
        public Emp_offense_Penalty()
        {
            this.Emp_offense = new HashSet<Emp_offense>();
        }
    
        public int Id { get; set; }
        public string Penalty_Name { get; set; }
    
        public virtual ICollection<Emp_offense> Emp_offense { get; set; }
    }
}
