//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_TrainingWS_temporary
    {
        public int Id { get; set; }
        public string Train_NumberWS { get; set; }
        public string Train_Header { get; set; }
        public string Train_HeaderThai { get; set; }
        public string Train_DateWS { get; set; }
        public Nullable<int> Train_Status { get; set; }
        public string Trai_NameArea { get; set; }
        public string Trai_Rev { get; set; }
        public string Train_DateChkSendMail { get; set; }
        public string SendMail { get; set; }
    }
}
