//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_sendEmailSession
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PssExpire { get; set; }
        public string Date_Input { get; set; }
        public string Time_Input { get; set; }
        public string WSnumber { get; set; }
        public string WSLine { get; set; }
    }
}
