//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_ImportEx
    {
        public Emp_ImportEx()
        {
            this.Emp_ImportChkCol = new HashSet<Emp_ImportChkCol>();
            this.Emp_ImportNotUseCol = new HashSet<Emp_ImportNotUseCol>();
        }
    
        public int Id { get; set; }
        public string EmpExNamesheet { get; set; }
        public string EmpExColEnd { get; set; }
    
        public virtual ICollection<Emp_ImportChkCol> Emp_ImportChkCol { get; set; }
        public virtual ICollection<Emp_ImportNotUseCol> Emp_ImportNotUseCol { get; set; }
    }
}
