//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_TrainingWsDate
    {
        public int Id { get; set; }
        public int E_TrainWsHeader_Id { get; set; }
        public string Date { get; set; }
        public string Training_dateSt { get; set; }
        public string Trai_Times { get; set; }
        public string Trai_Timess { get; set; }
        public string Training_dateEnd { get; set; }
        public string Trai_TimendT { get; set; }
        public string Trai_TimendTs { get; set; }
        public string Trai_House { get; set; }
        public string Trai_Minutices { get; set; }
        public string Train_Date { get; set; }
        public string Train_Hour { get; set; }
        public string Train_Min { get; set; }
        public string Train_WsName { get; set; }
    }
}
