//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_TrainingHeader
    {
        public Emp_TrainingHeader()
        {
            this.Emp_TrainingDetail = new HashSet<Emp_TrainingDetail>();
        }
    
        public int Id { get; set; }
        public string CourseHeader { get; set; }
        public Nullable<System.DateTime> Training_dateSt { get; set; }
        public string Trai_Times { get; set; }
        public string Trai_Timess { get; set; }
        public Nullable<System.DateTime> Training_dateEnd { get; set; }
        public string Trai_TimendT { get; set; }
        public string Trai_TimendTs { get; set; }
        public string Trai_House { get; set; }
        public string Trai_Minutices { get; set; }
        public string Train_Location { get; set; }
        public Nullable<int> Train_Price { get; set; }
        public string Train_Name { get; set; }
        public string Train_Date { get; set; }
        public string Train_Hour { get; set; }
        public string Train_Min { get; set; }
        public string Train_WsFileName { get; set; }
        public Nullable<int> Trai_Temporary_Id { get; set; }
        public string Train_DateWS { get; set; }
        public string Train_EmpId { get; set; }
        public string Training_Ws_Temp_id { get; set; }
    
        public virtual ICollection<Emp_TrainingDetail> Emp_TrainingDetail { get; set; }
    }
}
