//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSignature
    {
        public int ID { get; set; }
        public int EmpId { get; set; }
        public string SignaturePath { get; set; }
        public byte[] SignatureImage { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
