//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumLocationType
    {
        public EnumLocationType()
        {
            this.MasterLocations = new HashSet<MasterLocation>();
        }
    
        public int Id { get; set; }
        public string TextEnum { get; set; }
        public string TextEnus { get; set; }
        public string TextJajp { get; set; }
        public string TextThth { get; set; }
        public string TextZhch { get; set; }
    
        public virtual ICollection<MasterLocation> MasterLocations { get; set; }
    }
}
