//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int GMB_Id { get; set; }
        public int USG_Id { get; set; }
        public int USE_Id { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
