//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_func_rights
    {
        public int hr_rig_item { get; set; }
        public string hr_rig_desc { get; set; }
        public Nullable<int> RIH_Id { get; set; }
    }
}
