//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_LogEmployees
    {
        public int Id { get; set; }
        public string HR_Function_Name { get; set; }
        public string HR_Detail_Work { get; set; }
        public string HR_UserName { get; set; }
        public string HR_IdEmp { get; set; }
        public string HR_Department { get; set; }
        public string HR_Position { get; set; }
        public string HR_Date { get; set; }
    }
}
