//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_InputData
    {
        public int INP_Id { get; set; }
        public int INP_Year { get; set; }
        public int INP_Month { get; set; }
        public string INP_Plant { get; set; }
        public string INP_DocumentNo { get; set; }
        public string INP_DrawingNo { get; set; }
        public decimal INP_Quantity { get; set; }
        public string INP_Memo { get; set; }
        public System.DateTime INP_EditDate { get; set; }
        public string INP_EditBy { get; set; }
        public string STO_Code { get; set; }
        public string STK_Code { get; set; }
    
        public virtual Inventory_StockCode Inventory_StockCode { get; set; }
        public virtual Inventory_Store Inventory_Store { get; set; }
    }
}
