//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_DefineReport
    {
        public int DEF_Id { get; set; }
        public int LOC_Id { get; set; }
        public string STO_Code { get; set; }
        public string STK_Code { get; set; }
    
        public virtual Inventory_Location Inventory_Location { get; set; }
        public virtual Inventory_StockCode Inventory_StockCode { get; set; }
        public virtual Inventory_Store Inventory_Store { get; set; }
    }
}
