//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Store
    {
        public Inventory_Store()
        {
            this.Inventory_DefineReport = new HashSet<Inventory_DefineReport>();
            this.Inventory_InputData = new HashSet<Inventory_InputData>();
        }
    
        public string STO_Code { get; set; }
        public string STO_Group { get; set; }
        public string STO_DescT { get; set; }
        public string STO_DescE { get; set; }
        public int STO_Lock { get; set; }
        public int STO_Hide { get; set; }
        public string STO_Memo1 { get; set; }
        public string STO_Memo2 { get; set; }
        public string STO_Memo3 { get; set; }
        public string STO_EditBy { get; set; }
        public System.DateTime STO_EditDate { get; set; }
    
        public virtual ICollection<Inventory_DefineReport> Inventory_DefineReport { get; set; }
        public virtual ICollection<Inventory_InputData> Inventory_InputData { get; set; }
    }
}
