//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Log
    {
        public int IPL_Id { get; set; }
        public string IPL_Table { get; set; }
        public string IPL_Detail { get; set; }
        public string IPL_Mode { get; set; }
        public Nullable<System.DateTime> IPL_EditDate { get; set; }
        public string IPL_EditBy { get; set; }
    }
}
