//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_StockCode
    {
        public Inventory_StockCode()
        {
            this.Inventory_DefineReport = new HashSet<Inventory_DefineReport>();
            this.Inventory_InputData = new HashSet<Inventory_InputData>();
            this.Inventory_StandardCost = new HashSet<Inventory_StandardCost>();
        }
    
        public string STK_Code { get; set; }
        public string STK_Code2 { get; set; }
        public string STK_Group { get; set; }
        public string STK_PartName { get; set; }
        public string STK_DrawingNo { get; set; }
        public string STK_ModelNo { get; set; }
        public string STK_DescE1 { get; set; }
        public string STK_DescE2 { get; set; }
        public string STK_DescE3 { get; set; }
        public string STK_UnitName { get; set; }
        public Nullable<int> STK_Hide { get; set; }
        public Nullable<int> STK_Lock { get; set; }
        public string STK_EditBy { get; set; }
        public System.DateTime STK_EditDate { get; set; }
    
        public virtual ICollection<Inventory_DefineReport> Inventory_DefineReport { get; set; }
        public virtual ICollection<Inventory_InputData> Inventory_InputData { get; set; }
        public virtual ICollection<Inventory_StandardCost> Inventory_StandardCost { get; set; }
    }
}
