//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Group
    {
        public int Id { get; set; }
        public string GMD_DrawingNo { get; set; }
        public string GMD_Group { get; set; }
        public string GMD_GroupDescription { get; set; }
        public string GMD_ModelNo { get; set; }
        public string GMD_PartName { get; set; }
    }
}
