//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Location
    {
        public Inventory_Location()
        {
            this.Inventory_DefineReport = new HashSet<Inventory_DefineReport>();
        }
    
        public int LOC_Id { get; set; }
        public string LOC_Name { get; set; }
        public string LOC_Type { get; set; }
        public string LOC_Group { get; set; }
        public Nullable<int> LOC_Plant { get; set; }
        public Nullable<int> LOC_Order { get; set; }
    
        public virtual ICollection<Inventory_DefineReport> Inventory_DefineReport { get; set; }
    }
}
