//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_StandardCost
    {
        public int STD_Id { get; set; }
        public string STK_Code { get; set; }
        public string STK_DrawingNo { get; set; }
        public decimal STD_Cost { get; set; }
        public string STD_Memo1 { get; set; }
        public string STD_Memo2 { get; set; }
        public int STD_Year { get; set; }
    
        public virtual Inventory_StockCode Inventory_StockCode { get; set; }
    }
}
