//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryRecord
    {
        public int Id { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionNo { get; set; }
        public int TransactionLineNo { get; set; }
        public int TransactionCount { get; set; }
        public int EnumTransactionTypeId { get; set; }
        public int MasterItemId { get; set; }
        public Nullable<decimal> Length { get; set; }
        public int MasterLocationId { get; set; }
        public string LotNo { get; set; }
        public string LotSubNo { get; set; }
        public Nullable<int> ProjectCodeHeaderId { get; set; }
        public Nullable<int> ProjectCodeDetailId { get; set; }
        public string UserLotNo { get; set; }
        public string UserLotSubNo { get; set; }
        public decimal ItemQty { get; set; }
        public decimal AltItemQty { get; set; }
        public string OriginalNoteNo { get; set; }
        public string Remark { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual MasterItem MasterItem { get; set; }
        public virtual MasterLocation MasterLocation { get; set; }
    }
}
