//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDebitCreditNoteHeader
    {
        public int Id { get; set; }
        public string InvoiceCreditDebitNoteNo { get; set; }
        public int EnumDebitCreditTypeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime PaymentDueDate { get; set; }
        public string IssueReason { get; set; }
        public int MasterCustomerId { get; set; }
        public int MasterInvoiceId { get; set; }
        public string InvoiceName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostalCode { get; set; }
        public string TelephoneNo1 { get; set; }
        public string TelephoneNo2 { get; set; }
        public string FaxNo { get; set; }
        public int EnumRoundTypeId { get; set; }
        public int MasterCurrencyId { get; set; }
        public int EnumExchangeRateTypeId { get; set; }
        public Nullable<int> EnumAccDocTypeId { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<int> PaymentMonth { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Vat { get; set; }
        public decimal SubTotalAmountNative { get; set; }
        public decimal ExchangeRate { get; set; }
        public int MasterCurrencyNativeCurrencyId { get; set; }
        public decimal DomesticPpn { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal GrandTotalNative { get; set; }
        public bool IsInvoiceIssued { get; set; }
        public Nullable<System.DateTime> InvoiceIssuedDate { get; set; }
        public bool IsInvoiceExportedToAcc { get; set; }
        public int MasterNumberingRuleId { get; set; }
        public bool IsPrinted { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public string Remark { get; set; }
        public string Remark2 { get; set; }
        public bool IsDelete { get; set; }
        public decimal WithholdingTax { get; set; }
        public decimal PaymentAmount { get; set; }
        public bool IsVoucherPrinted { get; set; }
        public Nullable<System.DateTime> VoucherPrintedDate { get; set; }
        public int PaymentTotalCount { get; set; }
        public decimal TotalClearingBillingAmount { get; set; }
        public decimal RestBillingAmount { get; set; }
        public int EnumPaymentStatusId { get; set; }
        public Nullable<int> MasterVatHeaderId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterCustomer MasterCustomer { get; set; }
        public virtual MasterInvoice MasterInvoice { get; set; }
    }
}
