//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveEmployee
    {
        public string Leave_startdate { get; set; }
        public string Leave_enddate { get; set; }
        public int EmpList_Id { get; set; }
        public string Title_EN { get; set; }
        public string FName_EN { get; set; }
        public string LName_EN { get; set; }
        public string NName_EN { get; set; }
        public string DeptCode { get; set; }
        public string DeptDesc { get; set; }
        public string Position { get; set; }
        public string CostCenterName { get; set; }
        public Nullable<double> Business { get; set; }
        public Nullable<double> SickCert { get; set; }
        public Nullable<double> Vacation { get; set; }
        public Nullable<double> Other { get; set; }
        public Nullable<double> Sick { get; set; }
        public Nullable<double> SVacation { get; set; }
        public Nullable<double> SpecialBusiness { get; set; }
    }
}
