//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Log_Id { get; set; }
        public string Log_System { get; set; }
        public string Log_Type { get; set; }
        public string Log_Detail { get; set; }
        public string Log_Action { get; set; }
        public Nullable<System.DateTime> Log_Date { get; set; }
        public string Log_by { get; set; }
        public int Log_Action_Id { get; set; }
    }
}
