//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotRunNumber
    {
        public int LOT_Id { get; set; }
        public string LOT_TagId { get; set; }
        public string LOT_StockCode { get; set; }
        public string LOT_Prefix { get; set; }
        public Nullable<int> LOT_SubFix { get; set; }
        public string LOT_CustomerCode { get; set; }
    }
}
