//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterVendor
    {
        public MasterVendor()
        {
            this.MasterLocations = new HashSet<MasterLocation>();
            this.ReceivingActualHeaders = new HashSet<ReceivingActualHeader>();
            this.CustomerOrderDetails = new HashSet<CustomerOrderDetail>();
        }
    
        public int Id { get; set; }
        public string VendorCode { get; set; }
        public string PersonInCharge { get; set; }
        public string EmailTo { get; set; }
        public string EmailCC1 { get; set; }
        public string EmailCC2 { get; set; }
        public string EmailCC3 { get; set; }
        public string EmailCC4 { get; set; }
        public string EmailCC5 { get; set; }
        public string EmailCC6 { get; set; }
        public string EmailCC7 { get; set; }
        public string EmailCC8 { get; set; }
        public int EnumRoundTypeId { get; set; }
        public int MasterCurrencyId { get; set; }
        public decimal PaymentTerm { get; set; }
        public string PaymentPeriod { get; set; }
        public string PaymentCondition { get; set; }
        public int EnumExchangeRateTypeId { get; set; }
        public int MasterVatHeaderId { get; set; }
        public int EnumReturnTypeId { get; set; }
        public Nullable<decimal> DeliveryLt { get; set; }
        public int MasterBusinessPartnerId { get; set; }
        public string TaxId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> MasterAccHeaderForAccId { get; set; }
        public Nullable<int> MasterIncotermId { get; set; }
        public int EnumBranchTypeId { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> MasterVendorGroupId { get; set; }
        public bool IsPOExcel { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterBusinessPartner MasterBusinessPartner { get; set; }
        public virtual ICollection<MasterLocation> MasterLocations { get; set; }
        public virtual ICollection<ReceivingActualHeader> ReceivingActualHeaders { get; set; }
        public virtual ICollection<CustomerOrderDetail> CustomerOrderDetails { get; set; }
    }
}
