//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterItem
    {
        public MasterItem()
        {
            this.MasterStructure2 = new HashSet<MasterStructure2>();
            this.MasterStructure21 = new HashSet<MasterStructure2>();
            this.MasterStructure22 = new HashSet<MasterStructure2>();
            this.StockBooks = new HashSet<StockBook>();
            this.InventoryRecords = new HashSet<InventoryRecord>();
            this.StocktakingActualDetails = new HashSet<StocktakingActualDetail>();
            this.ReceivingActualDetails = new HashSet<ReceivingActualDetail>();
            this.MfgMaterialsIssueDetails = new HashSet<MfgMaterialsIssueDetail>();
            this.CustomerOrderDetails = new HashSet<CustomerOrderDetail>();
            this.ShippingActualDetails = new HashSet<ShippingActualDetail>();
        }
    
        public int Id { get; set; }
        public string ItemNo { get; set; }
        public string ModelNo { get; set; }
        public decimal RevisionNo { get; set; }
        public string ItemShortName { get; set; }
        public string ItemName { get; set; }
        public string ItemSpec { get; set; }
        public string OriginalLength { get; set; }
        public string ItemGroup { get; set; }
        public string MakerName { get; set; }
        public int EnumItemTypeId { get; set; }
        public Nullable<int> EnumMfgTypeId { get; set; }
        public Nullable<int> EnumPurTypeId { get; set; }
        public Nullable<int> EnumAbcClassId { get; set; }
        public int MasterUnitId { get; set; }
        public int MasterUnitAltItemUnitCodeId { get; set; }
        public int EnumIssueTypeId { get; set; }
        public int EnumStockControlTypeId { get; set; }
        public bool IsLotControl { get; set; }
        public bool IsCyclicCounting { get; set; }
        public Nullable<decimal> CyclicCountingPeriod { get; set; }
        public bool IsOeStockBooking { get; set; }
        public bool IsRecycle { get; set; }
        public bool IsMfgInsp { get; set; }
        public int MasterLocationId { get; set; }
        public Nullable<decimal> LowLevelCode { get; set; }
        public bool IsCustomGsp { get; set; }
        public Nullable<int> MasterCustomGspId { get; set; }
        public int MasterAccCodeId { get; set; }
        public Nullable<int> MasterAccCodeAssetId { get; set; }
        public bool IsActive { get; set; }
        public bool IsSales { get; set; }
        public decimal EvaluatedUnitCost { get; set; }
        public string Remark { get; set; }
        public Nullable<int> MasterAccGroupForAccId { get; set; }
        public int MasterVatItemGroupId { get; set; }
        public Nullable<int> MasterItemDiscountGroupId { get; set; }
        public decimal LotSize { get; set; }
        public decimal NumberOfLabelPrint { get; set; }
        public decimal NumberOfPalette { get; set; }
        public Nullable<int> MasterNumberingRuleId { get; set; }
        public decimal ShelfLife { get; set; }
        public bool IsDirectOrder { get; set; }
        public bool IsAllowPriceChange { get; set; }
        public bool IsAllowSalesPriceChange { get; set; }
        public decimal NetWeight { get; set; }
        public decimal GrossWeight { get; set; }
        public decimal Height { get; set; }
        public decimal Width { get; set; }
        public decimal Depth { get; set; }
        public Nullable<int> MasterJobId { get; set; }
        public bool IsSupply { get; set; }
        public Nullable<int> BIGroup1Id { get; set; }
        public Nullable<int> BIGroup2Id { get; set; }
        public Nullable<int> BIGroup3Id { get; set; }
        public bool IsNotAllowCalculate { get; set; }
        public bool IsFinishInsp { get; set; }
        public decimal PurchaseLeadTime { get; set; }
        public decimal ShippingLeadTime { get; set; }
        public decimal ProductionLeadTime { get; set; }
        public Nullable<int> MasterCustomerId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterCustomer MasterCustomer { get; set; }
        public virtual ICollection<MasterStructure2> MasterStructure2 { get; set; }
        public virtual ICollection<MasterStructure2> MasterStructure21 { get; set; }
        public virtual ICollection<MasterStructure2> MasterStructure22 { get; set; }
        public virtual ICollection<StockBook> StockBooks { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
        public virtual MasterUnit MasterUnit1 { get; set; }
        public virtual MasterLocation MasterLocation { get; set; }
        public virtual ICollection<InventoryRecord> InventoryRecords { get; set; }
        public virtual ICollection<StocktakingActualDetail> StocktakingActualDetails { get; set; }
        public virtual ICollection<ReceivingActualDetail> ReceivingActualDetails { get; set; }
        public virtual ICollection<MfgMaterialsIssueDetail> MfgMaterialsIssueDetails { get; set; }
        public virtual ICollection<CustomerOrderDetail> CustomerOrderDetails { get; set; }
        public virtual ICollection<ShippingActualDetail> ShippingActualDetails { get; set; }
    }
}
