//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterUnit
    {
        public MasterUnit()
        {
            this.MasterItems = new HashSet<MasterItem>();
            this.MasterItems1 = new HashSet<MasterItem>();
            this.StockBooks = new HashSet<StockBook>();
            this.ReceivingActualDetails = new HashSet<ReceivingActualDetail>();
            this.ReceivingActualDetails1 = new HashSet<ReceivingActualDetail>();
            this.ReceivingActualDetails2 = new HashSet<ReceivingActualDetail>();
            this.MfgMaterialsIssueDetails = new HashSet<MfgMaterialsIssueDetail>();
            this.CustomerOrderDetails = new HashSet<CustomerOrderDetail>();
            this.CustomerOrderDetails1 = new HashSet<CustomerOrderDetail>();
            this.CustomerOrderDetails2 = new HashSet<CustomerOrderDetail>();
            this.ShippingActualDetails = new HashSet<ShippingActualDetail>();
            this.ShippingActualDetails1 = new HashSet<ShippingActualDetail>();
            this.ShippingActualDetails2 = new HashSet<ShippingActualDetail>();
            this.ShippingActualDetails3 = new HashSet<ShippingActualDetail>();
        }
    
        public int Id { get; set; }
        public string UnitCode { get; set; }
        public string UnitName1 { get; set; }
        public string UnitName2 { get; set; }
        public decimal RoundPlace { get; set; }
        public string Note { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<MasterItem> MasterItems { get; set; }
        public virtual ICollection<MasterItem> MasterItems1 { get; set; }
        public virtual ICollection<StockBook> StockBooks { get; set; }
        public virtual ICollection<ReceivingActualDetail> ReceivingActualDetails { get; set; }
        public virtual ICollection<ReceivingActualDetail> ReceivingActualDetails1 { get; set; }
        public virtual ICollection<ReceivingActualDetail> ReceivingActualDetails2 { get; set; }
        public virtual ICollection<MfgMaterialsIssueDetail> MfgMaterialsIssueDetails { get; set; }
        public virtual ICollection<CustomerOrderDetail> CustomerOrderDetails { get; set; }
        public virtual ICollection<CustomerOrderDetail> CustomerOrderDetails1 { get; set; }
        public virtual ICollection<CustomerOrderDetail> CustomerOrderDetails2 { get; set; }
        public virtual ICollection<ShippingActualDetail> ShippingActualDetails { get; set; }
        public virtual ICollection<ShippingActualDetail> ShippingActualDetails1 { get; set; }
        public virtual ICollection<ShippingActualDetail> ShippingActualDetails2 { get; set; }
        public virtual ICollection<ShippingActualDetail> ShippingActualDetails3 { get; set; }
    }
}
