//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterLocation
    {
        public MasterLocation()
        {
            this.MasterItems = new HashSet<MasterItem>();
            this.StockBooks = new HashSet<StockBook>();
            this.InventoryRecords = new HashSet<InventoryRecord>();
            this.StocktakingActualDetails = new HashSet<StocktakingActualDetail>();
            this.ReceivingActualDetails = new HashSet<ReceivingActualDetail>();
            this.MfgMaterialsIssueDetails = new HashSet<MfgMaterialsIssueDetail>();
            this.ShippingActualDetails = new HashSet<ShippingActualDetail>();
        }
    
        public int Id { get; set; }
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public int EnumLocationTypeId { get; set; }
        public bool IsMrpTarget { get; set; }
        public Nullable<int> MasterDepartmentId { get; set; }
        public Nullable<int> MasterVendorId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<MasterItem> MasterItems { get; set; }
        public virtual ICollection<StockBook> StockBooks { get; set; }
        public virtual ICollection<InventoryRecord> InventoryRecords { get; set; }
        public virtual ICollection<StocktakingActualDetail> StocktakingActualDetails { get; set; }
        public virtual EnumLocationType EnumLocationType { get; set; }
        public virtual MasterVendor MasterVendor { get; set; }
        public virtual ICollection<ReceivingActualDetail> ReceivingActualDetails { get; set; }
        public virtual ICollection<MfgMaterialsIssueDetail> MfgMaterialsIssueDetails { get; set; }
        public virtual ICollection<ShippingActualDetail> ShippingActualDetails { get; set; }
    }
}
