//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterStructure2
    {
        public int Id { get; set; }
        public int PId { get; set; }
        public int DisplayIndex { get; set; }
        public int MasterParentItemId { get; set; }
        public int MasterChildItemId { get; set; }
        public System.DateTime EffectFromDate { get; set; }
        public Nullable<System.DateTime> EffectToDate { get; set; }
        public decimal NumeratorQty { get; set; }
        public decimal DenominatorQty { get; set; }
        public decimal StructureLossFillRate { get; set; }
        public Nullable<int> EnumSupplyTypeId { get; set; }
        public bool IsSubstitution { get; set; }
        public Nullable<int> MasterItemSubstitutionId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterItem MasterItem { get; set; }
        public virtual MasterItem MasterItem1 { get; set; }
        public virtual MasterItem MasterItem2 { get; set; }
    }
}
