//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterCustomer
    {
        public MasterCustomer()
        {
            this.InvoiceDebitCreditNoteHeaders = new HashSet<InvoiceDebitCreditNoteHeader>();
            this.InvoiceHeaders = new HashSet<InvoiceHeader>();
            this.MasterItems = new HashSet<MasterItem>();
            this.CustomerOrderHeaders = new HashSet<CustomerOrderHeader>();
            this.ShippingActualHeaders = new HashSet<ShippingActualHeader>();
        }
    
        public int Id { get; set; }
        public string CustomerCode { get; set; }
        public int MasterInvoiceId { get; set; }
        public string PersonInCharge { get; set; }
        public string TelInside { get; set; }
        public string TelOutside { get; set; }
        public int EnumReturnTypeId { get; set; }
        public Nullable<int> MasterIncotermId { get; set; }
        public bool IsActive { get; set; }
        public int MasterBusinessPartnerId { get; set; }
        public bool IsOversea { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<InvoiceDebitCreditNoteHeader> InvoiceDebitCreditNoteHeaders { get; set; }
        public virtual ICollection<InvoiceHeader> InvoiceHeaders { get; set; }
        public virtual MasterBusinessPartner MasterBusinessPartner { get; set; }
        public virtual MasterInvoice MasterInvoice { get; set; }
        public virtual ICollection<MasterItem> MasterItems { get; set; }
        public virtual ICollection<CustomerOrderHeader> CustomerOrderHeaders { get; set; }
        public virtual ICollection<ShippingActualHeader> ShippingActualHeaders { get; set; }
    }
}
