//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterCompany
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName1 { get; set; }
        public string CompanyName2 { get; set; }
        public string CompanyShortName { get; set; }
        public System.DateTime EstDate { get; set; }
        public string PostalCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string AddressTH1 { get; set; }
        public string AddressTH2 { get; set; }
        public string TelephoneNo1 { get; set; }
        public string TelephoneNo2 { get; set; }
        public string FaxNo1 { get; set; }
        public string FaxNo2 { get; set; }
        public byte[] Logo { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string TaxId { get; set; }
        public string BranchCodeForAcc { get; set; }
        public int EnumBranchTypeId { get; set; }
        public string BranchName { get; set; }
        public string BankBranch { get; set; }
        public string BankSwiftCode { get; set; }
        public string BankAddress1 { get; set; }
        public string BankAddress2 { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
