//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MfgMaterialsIssueDetail
    {
        public int Id { get; set; }
        public int MfgResultDetailId { get; set; }
        public int IssueLineNo { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int MasterItemId { get; set; }
        public int StockBookId { get; set; }
        public int MasterLocationId { get; set; }
        public string UserLotNo { get; set; }
        public string UserLotSubNo { get; set; }
        public decimal ItemQty { get; set; }
        public decimal AltItemQty { get; set; }
        public string Remark { get; set; }
        public int MasterUnitCostTypeId { get; set; }
        public decimal EvaluatedUnitCost { get; set; }
        public decimal EvaluatedAmount { get; set; }
        public int MasterCurrencyId { get; set; }
        public Nullable<int> MfgStartId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterItem MasterItem { get; set; }
        public virtual MasterLocation MasterLocation { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
        public virtual StockBook StockBook { get; set; }
    }
}
