//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OCTWEBTESTEntities : DbContext
    {
        public OCTWEBTESTEntities()
            : base("name=OCTWEBTESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cap_Checkby> cap_Checkby { get; set; }
        public virtual DbSet<cap_Line> cap_Line { get; set; }
        public virtual DbSet<cap_LMD> cap_LMD { get; set; }
        public virtual DbSet<cap_Partname> cap_Partname { get; set; }
        public virtual DbSet<cap_PBlist> cap_PBlist { get; set; }
        public virtual DbSet<cap_PBmain> cap_PBmain { get; set; }
        public virtual DbSet<cap_PNL> cap_PNL { get; set; }
        public virtual DbSet<cap_PNofPBm> cap_PNofPBm { get; set; }
        public virtual DbSet<cap_POM> cap_POM { get; set; }
        public virtual DbSet<cap_Problemdetail> cap_Problemdetail { get; set; }
        public virtual DbSet<cap_Probleminform> cap_Probleminform { get; set; }
        public virtual DbSet<cap_Problempic> cap_Problempic { get; set; }
        public virtual DbSet<CM_Problem> CM_Problem { get; set; }
        public virtual DbSet<CM_TodoEvidence> CM_TodoEvidence { get; set; }
        public virtual DbSet<CM_TodoList> CM_TodoList { get; set; }
        public virtual DbSet<CoursesRecord> CoursesRecords { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DW_Fileshare> DW_Fileshare { get; set; }
        public virtual DbSet<DW_Formulas> DW_Formulas { get; set; }
        public virtual DbSet<DW_Model> DW_Model { get; set; }
        public virtual DbSet<DW_ModelProcess> DW_ModelProcess { get; set; }
        public virtual DbSet<DW_PartName> DW_PartName { get; set; }
        public virtual DbSet<DW_Process> DW_Process { get; set; }
        public virtual DbSet<Emp_CostCenter> Emp_CostCenter { get; set; }
        public virtual DbSet<emp_department> emp_department { get; set; }
        public virtual DbSet<Emp_ImportChkCol> Emp_ImportChkCol { get; set; }
        public virtual DbSet<Emp_ImportEx> Emp_ImportEx { get; set; }
        public virtual DbSet<Emp_ImportNotUseCol> Emp_ImportNotUseCol { get; set; }
        public virtual DbSet<Emp_offense> Emp_offense { get; set; }
        public virtual DbSet<Emp_offense_Levelwarning> Emp_offense_Levelwarning { get; set; }
        public virtual DbSet<Emp_offense_Penalty> Emp_offense_Penalty { get; set; }
        public virtual DbSet<emp_position> emp_position { get; set; }
        public virtual DbSet<Emp_TrainingDetail> Emp_TrainingDetail { get; set; }
        public virtual DbSet<Emp_TrainingHeader> Emp_TrainingHeader { get; set; }
        public virtual DbSet<Emp_TrainingWS_temporary> Emp_TrainingWS_temporary { get; set; }
        public virtual DbSet<Emp_Typesick> Emp_Typesick { get; set; }
        public virtual DbSet<Former_EmpList> Former_EmpList { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<Inventory_DefineReport> Inventory_DefineReport { get; set; }
        public virtual DbSet<Inventory_InputData> Inventory_InputData { get; set; }
        public virtual DbSet<Inventory_Location> Inventory_Location { get; set; }
        public virtual DbSet<Inventory_Log> Inventory_Log { get; set; }
        public virtual DbSet<Inventory_StandardCost> Inventory_StandardCost { get; set; }
        public virtual DbSet<Inventory_StockCode> Inventory_StockCode { get; set; }
        public virtual DbSet<Inventory_Store> Inventory_Store { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Mstk_EmpResip> Mstk_EmpResip { get; set; }
        public virtual DbSet<Mstk_Penalty> Mstk_Penalty { get; set; }
        public virtual DbSet<Mstk_Reason> Mstk_Reason { get; set; }
        public virtual DbSet<RightGroup> RightGroups { get; set; }
        public virtual DbSet<Right> Rights { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemSys> SystemSys { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserRight> UserRights { get; set; }
        public virtual DbSet<WSR_CompRule> WSR_CompRule { get; set; }
        public virtual DbSet<WSR_CompRuleType> WSR_CompRuleType { get; set; }
        public virtual DbSet<WSR_WorkingStandardProcessEdit> WSR_WorkingStandardProcessEdit { get; set; }
        public virtual DbSet<WSR_WorkingStandardTypeEdit> WSR_WorkingStandardTypeEdit { get; set; }
        public virtual DbSet<DeliveryTagPlan> DeliveryTagPlans { get; set; }
        public virtual DbSet<DepartmentEdit> DepartmentEdits { get; set; }
        public virtual DbSet<DWPic> DWPics { get; set; }
        public virtual DbSet<Emp_sendEmailSession> Emp_sendEmailSession { get; set; }
        public virtual DbSet<Emp_SickLeave> Emp_SickLeave { get; set; }
        public virtual DbSet<Former_EmpList_Newt> Former_EmpList_Newt { get; set; }
        public virtual DbSet<hr_func_rights> hr_func_rights { get; set; }
        public virtual DbSet<hr_LogEmployees> hr_LogEmployees { get; set; }
        public virtual DbSet<Inventory_Group> Inventory_Group { get; set; }
        public virtual DbSet<LotRunNumber> LotRunNumbers { get; set; }
        public virtual DbSet<Temp_Inventory_StockCode> Temp_Inventory_StockCode { get; set; }
        public virtual DbSet<UserDetailEdit> UserDetailEdits { get; set; }
        public virtual DbSet<WSR_WorkingStandardEdit> WSR_WorkingStandardEdit { get; set; }
        public virtual DbSet<WS_Training_Section> WS_Training_Section { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Emp_TrainingWsHeader> Emp_TrainingWsHeader { get; set; }
        public virtual DbSet<Emp_TrainingWsDate> Emp_TrainingWsDate { get; set; }
        public virtual DbSet<Emp_TrainingWsDetail> Emp_TrainingWsDetail { get; set; }
        public virtual DbSet<Emp_MasterRegion> Emp_MasterRegion { get; set; }
        public virtual DbSet<Emp_MasterTypeLayoff> Emp_MasterTypeLayoff { get; set; }
        public virtual DbSet<Emp_MasterNationality> Emp_MasterNationality { get; set; }
        public virtual DbSet<Emp_Transection_Leave> Emp_Transection_Leave { get; set; }
        public virtual DbSet<Emp_MasterReasonLeave> Emp_MasterReasonLeave { get; set; }
        public virtual DbSet<Emp_MasterStatusLeave> Emp_MasterStatusLeave { get; set; }
        public virtual DbSet<Emp_Holiday_sickleave> Emp_Holiday_sickleave { get; set; }
        public virtual DbSet<EmpList> EmpLists { get; set; }
        public virtual DbSet<LeaveEmployee> LeaveEmployees { get; set; }
        public virtual DbSet<Emp_Benefite> Emp_Benefite { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Rights01> Rights01 { get; set; }
        public virtual DbSet<DocumentActivityLog> DocumentActivityLogs { get; set; }
        public virtual DbSet<DocumentApprovalStep> DocumentApprovalSteps { get; set; }
        public virtual DbSet<DocumentList> DocumentLists { get; set; }
        public virtual DbSet<Equipment_repair_machine> Equipment_repair_machine { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
        public virtual DbSet<DocumentFormArea> DocumentFormAreas { get; set; }
        public virtual DbSet<DocumentSection> DocumentSections { get; set; }
        public virtual DbSet<EmployeeSignature> EmployeeSignatures { get; set; }
    }
}
