//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstk_Penalty
    {
        public int PenaltyID { get; set; }
        public string Pnlt_EN { get; set; }
        public string Pnlt_TH { get; set; }
    }
}
