//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstk_Reason
    {
        public int ReasonID { get; set; }
        public string Mstk_Reas_EN { get; set; }
        public string Mstk_Reas_TH { get; set; }
    }
}
