//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingActualDetail
    {
        public int Id { get; set; }
        public int ReceivingActualHeaderId { get; set; }
        public int ReceivingLineNo { get; set; }
        public int PurchaseOrderDetailId { get; set; }
        public int MasterItemId { get; set; }
        public Nullable<decimal> Length { get; set; }
        public int MasterLocationId { get; set; }
        public Nullable<int> MasterNumberingRuleId { get; set; }
        public string LotNo { get; set; }
        public string LotSubNo { get; set; }
        public string UserLotNo { get; set; }
        public string UserLotSubNo { get; set; }
        public decimal ReceivingQty { get; set; }
        public int MasterUnitReceivingUnitCodeId { get; set; }
        public decimal RcvItemQty { get; set; }
        public int MasterUnitRcvItemUnitCodeId { get; set; }
        public decimal RcvAltItemQty { get; set; }
        public int MasterUnitRcvAltItemUnitCodeId { get; set; }
        public bool IsPurchaseInsp { get; set; }
        public decimal InspOkQty { get; set; }
        public decimal InspNgQty { get; set; }
        public decimal InspUnitPrice { get; set; }
        public decimal InspAmount { get; set; }
        public decimal InspDiscountRate { get; set; }
        public decimal InspDiscountAmount { get; set; }
        public decimal InspTotalAmount { get; set; }
        public decimal InspVat { get; set; }
        public decimal InspGrandTotal { get; set; }
        public Nullable<int> MasterPurchaseItemId { get; set; }
        public int ReceivingCount { get; set; }
        public int EnumReturnTypeId { get; set; }
        public bool IsInspected { get; set; }
        public Nullable<int> ReceivingInspHeaderId { get; set; }
        public decimal EvaluatedUnitCost { get; set; }
        public string Remark { get; set; }
        public bool IsSupplyPartsIssued { get; set; }
        public Nullable<int> MasterAccCodeForAccId { get; set; }
        public decimal QTYperCarton { get; set; }
        public decimal NumberOfCarton { get; set; }
        public decimal NetWeightPerCarton { get; set; }
        public decimal TotalNetWeight { get; set; }
        public decimal GrossWeightPerCarton { get; set; }
        public decimal TotalGrossWeight { get; set; }
        public decimal MeasurementPerCarton { get; set; }
        public decimal TotalMeasurement { get; set; }
        public decimal InspNgQtyBuy { get; set; }
        public decimal TotalBuyingItemQty { get; set; }
        public Nullable<int> MasterAccGroupForAccId { get; set; }
        public bool IsLabelPrint { get; set; }
        public Nullable<System.DateTime> LabelPrintDate { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterItem MasterItem { get; set; }
        public virtual MasterLocation MasterLocation { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
        public virtual MasterUnit MasterUnit1 { get; set; }
        public virtual MasterUnit MasterUnit2 { get; set; }
        public virtual ReceivingActualHeader ReceivingActualHeader { get; set; }
    }
}
