//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingActualHeader
    {
        public ReceivingActualHeader()
        {
            this.ReceivingActualDetails = new HashSet<ReceivingActualDetail>();
        }
    
        public int Id { get; set; }
        public string ReceivingNo { get; set; }
        public System.DateTime ReceivingDate { get; set; }
        public int MasterVendorId { get; set; }
        public string DeliveryNoteNo { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<System.DateTime> RequestDueDate { get; set; }
        public bool IsInvoiceRegistered { get; set; }
        public Nullable<int> VendorInvoiceHeaderId { get; set; }
        public int MasterNumberingRuleId { get; set; }
        public bool IsInspectedComplete { get; set; }
        public bool IsDelete { get; set; }
        public string Remark { get; set; }
        public bool IsSupplyPartsIssuedComplete { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterVendor MasterVendor { get; set; }
        public virtual ICollection<ReceivingActualDetail> ReceivingActualDetails { get; set; }
    }
}
