//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightGroup
    {
        public RightGroup()
        {
            this.Rights = new HashSet<Right>();
            this.Rights01 = new HashSet<Rights01>();
        }
    
        public int RIG_Id { get; set; }
        public string RIG_Name { get; set; }
        public string RIG_Description { get; set; }
        public int SYS_Id { get; set; }
    
        public virtual SystemSys SystemSys { get; set; }
        public virtual ICollection<Right> Rights { get; set; }
        public virtual ICollection<Rights01> Rights01 { get; set; }
    }
}
