//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public Right()
        {
            this.UserRights = new HashSet<UserRight>();
        }
    
        public int RIH_Id { get; set; }
        public string RIH_Name { get; set; }
        public string RIH_Description { get; set; }
        public string RIH_Pages { get; set; }
        public int RIG_Id { get; set; }
    
        public virtual RightGroup RightGroup { get; set; }
        public virtual ICollection<UserRight> UserRights { get; set; }
    }
}
