//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingActualDetail
    {
        public int Id { get; set; }
        public int ShippingActualHeaderId { get; set; }
        public int ShippingActualLineNo { get; set; }
        public int CustomerOrderDetailId { get; set; }
        public int MasterItemId { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<int> StockBookId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> MasterLocationId { get; set; }
        public string LotNo { get; set; }
        public string LotSubNo { get; set; }
        public string UserLotNo { get; set; }
        public string UserLotSubNo { get; set; }
        public decimal ShpItemQty { get; set; }
        public int MasterUnitShpItemUnitCodeId { get; set; }
        public decimal ShpAltItemQty { get; set; }
        public int MasterUnitShpAltItemUnitCodeId { get; set; }
        public decimal ShippingQty { get; set; }
        public int MasterUnitShippingUnitCodeId { get; set; }
        public int ShippingCount { get; set; }
        public bool IsCustomerInsp { get; set; }
        public bool IsInspected { get; set; }
        public Nullable<int> CustomerInspHeaderId { get; set; }
        public decimal InspOkQty { get; set; }
        public decimal InspNgQty { get; set; }
        public decimal InspUnitPrice { get; set; }
        public decimal InspAmount { get; set; }
        public decimal InspDiscountRate { get; set; }
        public decimal InspDiscountAmount { get; set; }
        public decimal InspTotalAmount { get; set; }
        public decimal InspVat { get; set; }
        public decimal InspGrandTotal { get; set; }
        public int MasterUnitCostTypeId { get; set; }
        public decimal EvaluatedUnitCost { get; set; }
        public decimal EvaluatedAmount { get; set; }
        public int MasterCurrencyId { get; set; }
        public Nullable<int> MasterAccGroupForAccId { get; set; }
        public Nullable<int> MasterAccCodeForAccId { get; set; }
        public int MasterNativeCurrencyId { get; set; }
        public int EnumReturnTypeId { get; set; }
        public bool IsNgOrderCreated { get; set; }
        public decimal InspNgQtySell { get; set; }
        public decimal TotalSellingItemQty { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> MasterJobId { get; set; }
        public string CustomerPoNo { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual CustomerOrderDetail CustomerOrderDetail { get; set; }
        public virtual MasterItem MasterItem { get; set; }
        public virtual MasterLocation MasterLocation { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
        public virtual MasterUnit MasterUnit1 { get; set; }
        public virtual MasterUnit MasterUnit2 { get; set; }
        public virtual MasterUnit MasterUnit3 { get; set; }
        public virtual ShippingActualHeader ShippingActualHeader { get; set; }
        public virtual StockBook StockBook { get; set; }
    }
}
