//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingActualHeader
    {
        public ShippingActualHeader()
        {
            this.ShippingActualDetails = new HashSet<ShippingActualDetail>();
        }
    
        public int Id { get; set; }
        public string DeliveryNoteNo { get; set; }
        public int MasterNumberingRuleId { get; set; }
        public System.DateTime DeliveryNoteCreateDate { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public Nullable<System.DateTime> ShippingDueDate { get; set; }
        public string CustomerPONo { get; set; }
        public string DeliveryBillNo { get; set; }
        public int MasterCustomerId { get; set; }
        public string CustomerName { get; set; }
        public int MasterDestinationId { get; set; }
        public string DestinationName { get; set; }
        public int MasterInvoiceId { get; set; }
        public bool IsInspected { get; set; }
        public string Remark { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PostalCode { get; set; }
        public string TelephoneNo1 { get; set; }
        public string TelephoneNo2 { get; set; }
        public string FaxNo { get; set; }
        public int DeliveryLT { get; set; }
        public bool IsDeliveryNoteIssued { get; set; }
        public Nullable<System.DateTime> DeliveryNoteIssuedDate { get; set; }
        public bool IsInvoiceCreated { get; set; }
        public Nullable<int> InvoiceHeaderId { get; set; }
        public bool IsPrinted { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public bool IsDelete { get; set; }
        public bool IsDocumentAttached { get; set; }
        public Nullable<int> EnumHandyTransactionTypeId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual InvoiceHeader InvoiceHeader { get; set; }
        public virtual MasterCustomer MasterCustomer { get; set; }
        public virtual MasterInvoice MasterInvoice { get; set; }
        public virtual ICollection<ShippingActualDetail> ShippingActualDetails { get; set; }
    }
}
