//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBook_Structure_FccAssy_View2023
    {
        public Nullable<int> MasterChildItemId { get; set; }
        public string ChildItemNo { get; set; }
        public string ChildModelNo { get; set; }
        public string ChildItemShortName { get; set; }
        public string ItemGroup { get; set; }
        public string ItemName { get; set; }
        public decimal StockItemQty { get; set; }
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public int MasterLocationId { get; set; }
        public int EnumLocationTypeId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
