//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBook
    {
        public StockBook()
        {
            this.StocktakingActualDetails = new HashSet<StocktakingActualDetail>();
            this.MfgMaterialsIssueDetails = new HashSet<MfgMaterialsIssueDetail>();
            this.ShippingActualDetails = new HashSet<ShippingActualDetail>();
        }
    
        public int Id { get; set; }
        public int MasterItemId { get; set; }
        public Nullable<decimal> Length { get; set; }
        public int MasterLocationId { get; set; }
        public string LotNo { get; set; }
        public string LotSubNo { get; set; }
        public Nullable<int> ProjectCodeHeaderId { get; set; }
        public Nullable<int> ProjectCodeDetailId { get; set; }
        public string UserLotNo { get; set; }
        public string UserLotSubNo { get; set; }
        public decimal StockItemQty { get; set; }
        public decimal StockAltItemQty { get; set; }
        public decimal ReservedItemQty { get; set; }
        public Nullable<int> MasterCurrencyId { get; set; }
        public Nullable<int> MasterUnitUcTypeId { get; set; }
        public decimal EvaluatedUnitCost { get; set; }
        public decimal EvaluatedAmount { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<decimal> ShelfLife { get; set; }
        public int ProductAging { get; set; }
        public string Remark { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterItem MasterItem { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
        public virtual MasterLocation MasterLocation { get; set; }
        public virtual ICollection<StocktakingActualDetail> StocktakingActualDetails { get; set; }
        public virtual ICollection<MfgMaterialsIssueDetail> MfgMaterialsIssueDetails { get; set; }
        public virtual ICollection<ShippingActualDetail> ShippingActualDetails { get; set; }
    }
}
