//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocktakingActualDetail
    {
        public int Id { get; set; }
        public int StocktakingActualHeaderId { get; set; }
        public int StocktakingActualLineNo { get; set; }
        public string DocumentNo { get; set; }
        public int MasterItemId { get; set; }
        public int MasterLocationId { get; set; }
        public int StocktakingDetailId { get; set; }
        public int StockBookId { get; set; }
        public string UserLotNo { get; set; }
        public string UserLotSubNo { get; set; }
        public decimal ActualStockItemQty { get; set; }
        public decimal ActualStockAltItemQty { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ProjectCodeHeaderId { get; set; }
        public Nullable<int> ProjectCodeDetailId { get; set; }
        public string SendingTimestemp { get; set; }
        public Nullable<int> TagId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual MasterItem MasterItem { get; set; }
        public virtual MasterLocation MasterLocation { get; set; }
        public virtual StockBook StockBook { get; set; }
        public virtual StocktakingActualHeader StocktakingActualHeader { get; set; }
    }
}
