//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StocktakingActualHeader
    {
        public StocktakingActualHeader()
        {
            this.StocktakingActualDetails = new HashSet<StocktakingActualDetail>();
        }
    
        public int Id { get; set; }
        public string StocktakingActualNo { get; set; }
        public int MasterNumberingRuleId { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public int StocktakingHeaderId { get; set; }
        public System.DateTime StocktakingDate { get; set; }
        public string Remark { get; set; }
        public bool IsDelete { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<StocktakingActualDetail> StocktakingActualDetails { get; set; }
    }
}
