//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Inventory_StockCode
    {
        public string STK_Code { get; set; }
        public string STK_Code2 { get; set; }
        public string STK_Group { get; set; }
        public string STK_PartName { get; set; }
        public string STK_DrawingNo { get; set; }
        public string STK_ModelNo { get; set; }
        public string STK_DescE1 { get; set; }
        public string STK_DescE2 { get; set; }
        public string STK_UnitName { get; set; }
        public System.DateTime STK_EditDate { get; set; }
    }
}
