//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Thomas_Ogura_TESTDBEntities : DbContext
    {
        public Thomas_Ogura_TESTDBEntities()
            : base("name=Thomas_Ogura_TESTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InvoiceDebitCreditNoteHeader> InvoiceDebitCreditNoteHeaders { get; set; }
        public virtual DbSet<InvoiceHeader> InvoiceHeaders { get; set; }
        public virtual DbSet<MasterCompany> MasterCompanies { get; set; }
        public virtual DbSet<MasterCustomer> MasterCustomers { get; set; }
        public virtual DbSet<MasterBusinessPartner> MasterBusinessPartners { get; set; }
        public virtual DbSet<MasterInvoice> MasterInvoices { get; set; }
        public virtual DbSet<StockBook_Structure_FccAssy_View2023> StockBook_Structure_FccAssy_View2023 { get; set; }
        public virtual DbSet<MasterItem> MasterItems { get; set; }
        public virtual DbSet<MasterStructure2> MasterStructure2 { get; set; }
        public virtual DbSet<StockBook> StockBooks { get; set; }
        public virtual DbSet<MasterUnit> MasterUnits { get; set; }
        public virtual DbSet<MasterLocation> MasterLocations { get; set; }
        public virtual DbSet<InventoryRecord> InventoryRecords { get; set; }
        public virtual DbSet<StocktakingActualDetail> StocktakingActualDetails { get; set; }
        public virtual DbSet<StocktakingActualHeader> StocktakingActualHeaders { get; set; }
        public virtual DbSet<EnumLocationType> EnumLocationTypes { get; set; }
        public virtual DbSet<MasterVendor> MasterVendors { get; set; }
        public virtual DbSet<ReceivingActualDetail> ReceivingActualDetails { get; set; }
        public virtual DbSet<ReceivingActualHeader> ReceivingActualHeaders { get; set; }
        public virtual DbSet<MfgMaterialsIssueDetail> MfgMaterialsIssueDetails { get; set; }
        public virtual DbSet<CustomerOrderDetail> CustomerOrderDetails { get; set; }
        public virtual DbSet<CustomerOrderHeader> CustomerOrderHeaders { get; set; }
        public virtual DbSet<ShippingActualDetail> ShippingActualDetails { get; set; }
        public virtual DbSet<ShippingActualHeader> ShippingActualHeaders { get; set; }
    }
}
