//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.GroupMembers = new HashSet<GroupMember>();
        }
    
        public int USG_Id { get; set; }
        public string USG_Name { get; set; }
        public string USG_Memo { get; set; }
    
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
    }
}
