//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSR_WorkingStandardEdit
    {
        public int WS_Id { get; set; }
        public string WS_Name { get; set; }
        public string WS_Number { get; set; }
        public string WS_File { get; set; }
        public string WS_Note { get; set; }
        public int WST_Id { get; set; }
        public System.DateTime WS_Date { get; set; }
        public System.DateTime WS_Update { get; set; }
        public Nullable<int> WSP_Id { get; set; }
        public string WS_Rev { get; set; }
    }
}
