//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSR_WorkingStandardTypeEdit
    {
        public int WST_Id { get; set; }
        public string WST_Type { get; set; }
        public int WST_Dept { get; set; }
        public string WST_Note { get; set; }
    }
}
