//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCTWEB_NET45.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSR_CompRule
    {
        public int CR_Id { get; set; }
        public string CR_Name { get; set; }
        public string CR_File { get; set; }
        public string CR_Note { get; set; }
        public int CRT_Id { get; set; }
        public System.DateTime CR_Date { get; set; }
        public int CR_Rev { get; set; }
        public System.DateTime CR_Update { get; set; }
        public string CR_Number { get; set; }
    }
}
